// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xeqgwvnhezpjhwsqkzml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlcWd3dm5oZXpwamh3c3Frem1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDIwNjEsImV4cCI6MjA3MjM3ODA2MX0.grd_mad32Tv1WOY_ojVhI7-Sdt_Uc6fVKeE_DrS3lHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});